#!/bin/bash -e

cd ${0%*/*}

if [ ! -e Dockerfile ]; then
	echo "ERROR: Dockerfile is missing."
	exit 1
fi

if ! (which wget > /dev/null 2>&1); then
	echo "wget is required to build BFB"
	exit 1
fi

if ! (which podman > /dev/null 2>&1); then
        echo "podman is required to build BFB"
        exit 1
fi

DISTRO="tumbleweed"
DISTRO_VERSION="1.0"
BF_RELEASE="4.0.2"
DOCA_VERSION="2.0.2"
IMAGE_TYPE=${IMAGE_TYPE:-"prod"}
CUSTOM_VERSION=${CUSTOM_VERSION:-""}
NV_BASE_URL=${NV_BASE_URL:-"https://linux.mellanox.com/public/repo"}

WDIR=/tmp/${DISTRO}${DISTRO_VERSION}.$$

mkdir -p $WDIR/bootimages

wget -P $WDIR/bootimages -r --no-verbose --no-directories -l1 --no-parent -A 'mlxbf-bootimages*.aarch64.rpm' ${NV_BASE_URL}/bluefield/${BF_RELEASE}/bootimages/${IMAGE_TYPE}/

wget -P $WDIR/bootimages -r --no-verbose --no-directories ${NV_BASE_URL}/doca/2.2.0/centos7.6/aarch64/mlxbf-bfscripts-3.6.0-1.el7.noarch.rpm

cp 	Dockerfile \
	create_bfb \
	install.sh \
	../../common/tools/qemu-aarch64-static \
	$WDIR

cd $WDIR

podman build --arch=arm64 --network host -t bfb_runtime_${DISTRO}${DISTRO_VERSION} -f Dockerfile .
#podman run -it --rm --privileged
podman run --arch=arm64 --rm --privileged \
	-v $WDIR:/workspace \
	--name BlueField_OS_${DISTRO}_${DISTRO_VERSION} \
	--mount type=bind,source=/dev,target=/dev \
	--mount type=bind,source=/sys,target=/sys \
	--mount type=bind,source=/proc,target=/proc \
	bfb_runtime_${DISTRO}${DISTRO_VERSION}

readlink -f *.bfb

echo "Default root password is: linux"
